version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  # postgres:
  #   container_name: postgres
  #   image: postgres:15-alpine
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_PASSWORD=api
  #     - POSTGRES_USER=api
  #     - POSTGRES_DB=api
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - 5050:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@api.com
  #     - PGADMIN_DEFAULT_PASSWORD=api

# volumes:
#   postgres-data:
